// Auto-generated at build time. Do not commit.
window.__GENKI_CONFIG__ = {
  "SUPABASE_URL": "REPLACE_WITH_SUPABASE_URL",
  "SUPABASE_ANON_KEY": "REPLACE_WITH_SUPABASE_ANON_KEY",
  "SQUARE_APP_ID": "REPLACE_WITH_SQUARE_APP_ID",
  "SQUARE_LOCATION_ID": "REPLACE_WITH_SQUARE_LOCATION_ID"
};
